### ISSUE TITLE
LaunchGIN.bat opens but instantly closes

### ISSUE THREAD

**Issue by weixian446** [TheUnpunished/gintool#6]
When trying to launch launchgin.bat, it leads me to instant closing. The program stays for a bit more when launched as admin though

**Comment by TheUnpunished** [comment]
Do you have JRE/JDK 11 installed?
11 or higher.

**Comment by weixian446** [comment]
> Do you have JRE/JDK 11 installed? 11 or higher.
yes, i have

**Comment by TheUnpunished** [comment]
Make sure you have it in your PATH
[https://www.java.com/en/download/help/path.html](https://www.java.com/en/download/help/path.html)

**Comment by weixian446** [comment]
> Make sure you have it in your PATH https://www.java.com/en/download/help/path.html

i edited the path but it still does not run even via cmd. what should the exact path be?

**Comment by TheUnpunished** [comment]
`<JRE/JDK installation path>\bin`

**Comment by weixian446** [comment]
> `<JRE/JDK installation path>\bin`

did exactly like this, but still it fails to work

**Comment by TheUnpunished** [comment]
What's the output of the program?

**Comment by weixian446** [comment]
> What's the output of the program?

not inner or outer command executed and so on

**Comment by TheUnpunished** [comment]
Run the bat file through the command prompt. It will show you the output without closing.

**Comment by weixian446** [comment]
> Run the bat file through the command prompt. It will show you the output without closing.

ok, it helped me to open. but one more problem appeared: when launching through cmd it still says that not inner or outer command

**Comment by TheUnpunished** [comment]
That means you did not set up the PATH variable correctly.
